import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import '../l10n/app_localizations.dart';
import '../models/flashcard.dart';
import '../stores/flashcard_store.dart';

/// Camera screen that scans a GemMate QR code and imports the flashcard deck.
/// Also supports picking a QR code image from the photo gallery.
class QrScanScreen extends StatefulWidget {
  const QrScanScreen({super.key});

  @override
  State<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends State<QrScanScreen> {
  final MobileScannerController _ctrl = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    facing: CameraFacing.back,
  );

  bool _processing = false;
  bool _torchOn = false;
  String? _error;

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  // ── Gallery import ──────────────────────────────────────────────────────────

  Future<void> _pickFromGallery() async {
    if (_processing) return;
    final file = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (file == null) return;

    setState(() { _processing = true; _error = null; });
    try {
      final result = await _ctrl.analyzeImage(file.path);
      final raw = result?.barcodes.firstOrNull?.rawValue;
      if (raw == null || raw.isEmpty) {
        if (mounted) {
          setState(() {
            _error = AppLocalizations.of(context).noQrInImage;
            _processing = false;
          });
        }
        return;
      }
      setState(() => _processing = false);
      _tryImport(raw);
    } catch (e) {
      if (mounted) setState(() { _error = 'Gallery scan error: $e'; _processing = false; });
    }
  }

  void _onDetect(BarcodeCapture capture) {
    if (_processing) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null || raw.isEmpty) return;
    _tryImport(raw);
  }

  Future<void> _tryImport(String raw) async {
    setState(() {
      _processing = true;
      _error = null;
    });

    try {
      final dynamic decoded = jsonDecode(raw);
      if (decoded is! Map<String, dynamic>) throw const FormatException('Not an object');

      final version = decoded['v'];
      if (version != 1) throw const FormatException('Unknown payload version');

      final deckName = decoded['n'] as String? ?? 'Imported Deck';
      final cardsRaw = decoded['c'];
      if (cardsRaw is! List) throw const FormatException('Missing cards array');

      final groupId = 'qr_${DateTime.now().millisecondsSinceEpoch}';
      final cards = <Flashcard>[];

      for (int i = 0; i < cardsRaw.length; i++) {
        final item = cardsRaw[i];
        if (item is! Map) continue;
        final front = item['f']?.toString() ?? '';
        final back = item['b']?.toString() ?? '';
        if (front.isEmpty && back.isEmpty) continue;
        cards.add(Flashcard(
          id: '${groupId}_$i',
          groupId: groupId,
          groupName: deckName,
          front: front,
          back: back,
        ));
      }

      if (cards.isEmpty) throw const FormatException('No valid cards found');

      FlashcardStore().addCards(cards);

      if (mounted) {
        await _ctrl.stop();
        _showSuccess(deckName, cards.length);
      }
    } on FormatException catch (e) {
      if (mounted) {
        setState(() {
          _error = 'Invalid QR code: ${e.message}';
          _processing = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = 'Could not read QR code. Make sure it was generated by GemMate.';
          _processing = false;
        });
      }
    }
  }

  void _showSuccess(String deckName, int count) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        title: const Row(children: [
          Icon(Icons.check_circle, color: Color(0xFF06D6A0)),
          SizedBox(width: 8),
          Text('Deck Imported!'),
        ]),
        content: Text(
          'Successfully imported $count card${count == 1 ? '' : 's'} '
          'into deck "$deckName".',
        ),
        actions: [
          FilledButton(
            onPressed: () {
              Navigator.pop(ctx); // close dialog
              Navigator.pop(context); // close scanner
            },
            child: const Text('Go to Flashcards'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan QR Code',
            style: TextStyle(fontWeight: FontWeight.bold)),
        actions: [
          IconButton(
            icon: const Icon(Icons.photo_library_outlined),
            tooltip: l10n.scanFromGallery,
            onPressed: _processing ? null : _pickFromGallery,
          ),
          IconButton(
            icon: Icon(_torchOn ? Icons.flash_on : Icons.flash_off),
            onPressed: () {
              _ctrl.toggleTorch();
              setState(() => _torchOn = !_torchOn);
            },
          ),
        ],
      ),
      body: Stack(
        children: [
          // Camera preview
          MobileScanner(
            controller: _ctrl,
            onDetect: _onDetect,
          ),

          // Overlay with cut-out guide
          _ScanOverlay(),

          // Processing indicator
          if (_processing)
            const Center(
              child: Card(
                child: Padding(
                  padding: EdgeInsets.all(24),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      CircularProgressIndicator(),
                      SizedBox(height: 12),
                      Text('Importing deck…'),
                    ],
                  ),
                ),
              ),
            ),

          // Error banner
          if (_error != null)
            Positioned(
              bottom: 32,
              left: 24,
              right: 24,
              child: Material(
                borderRadius: BorderRadius.circular(14),
                color: Colors.red.shade800,
                child: Padding(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 16, vertical: 12),
                  child: Row(
                    children: [
                      const Icon(Icons.error_outline,
                          color: Colors.white, size: 20),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Text(
                          _error!,
                          style: const TextStyle(color: Colors.white),
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.close,
                            color: Colors.white, size: 18),
                        onPressed: () =>
                            setState(() => _error = null),
                        padding: EdgeInsets.zero,
                        constraints: const BoxConstraints(),
                      ),
                    ],
                  ),
                ),
              ),
            ),

          // Instruction + gallery hint
          if (!_processing)
            Positioned(
              bottom: _error != null ? 100 : 32,
              left: 0,
              right: 0,
              child: Column(
                children: [
                  Center(
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 20, vertical: 10),
                      decoration: BoxDecoration(
                        color: Colors.black54,
                        borderRadius: BorderRadius.circular(24),
                      ),
                      child: const Text(
                        'Point at a GemMate deck QR code',
                        style: TextStyle(color: Colors.white, fontSize: 14),
                      ),
                    ),
                  ),
                  const SizedBox(height: 10),
                  Center(
                    child: GestureDetector(
                      onTap: _pickFromGallery,
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 16, vertical: 7),
                        decoration: BoxDecoration(
                          color: Colors.black38,
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(color: Colors.white30),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.photo_library_outlined,
                                color: Colors.white70, size: 16),
                            const SizedBox(width: 6),
                            Text(
                              l10n.scanFromGallery,
                              style: const TextStyle(
                                  color: Colors.white70, fontSize: 12),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}

/// Semi-transparent overlay with a bright square cut-out to guide the user.
class _ScanOverlay extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomPaint(
      painter: _OverlayPainter(),
      child: const SizedBox.expand(),
    );
  }
}

class _OverlayPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    const cutSize = 240.0;
    final cx = size.width / 2;
    final cy = size.height / 2 - 30;
    final rect = Rect.fromCenter(
        center: Offset(cx, cy), width: cutSize, height: cutSize);

    // Dim background
    canvas.drawPath(
      Path.combine(
        PathOperation.difference,
        Path()..addRect(Rect.fromLTWH(0, 0, size.width, size.height)),
        Path()..addRRect(RRect.fromRectAndRadius(rect, const Radius.circular(12))),
      ),
      Paint()..color = Colors.black.withValues(alpha: 0.55),
    );

    // White border
    canvas.drawRRect(
      RRect.fromRectAndRadius(rect, const Radius.circular(12)),
      Paint()
        ..color = Colors.white
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2.5,
    );

    // Corner accents
    final cornerPaint = Paint()
      ..color = const Color(0xFF4361EE)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 4
      ..strokeCap = StrokeCap.round;

    const corner = 24.0;
    final l = rect.left;
    final t = rect.top;
    final r = rect.right;
    final b = rect.bottom;

    for (final path in [
      Path()
        ..moveTo(l + corner, t)
        ..lineTo(l, t)
        ..lineTo(l, t + corner),
      Path()
        ..moveTo(r - corner, t)
        ..lineTo(r, t)
        ..lineTo(r, t + corner),
      Path()
        ..moveTo(l + corner, b)
        ..lineTo(l, b)
        ..lineTo(l, b - corner),
      Path()
        ..moveTo(r - corner, b)
        ..lineTo(r, b)
        ..lineTo(r, b - corner),
    ]) {
      canvas.drawPath(path, cornerPaint);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter old) => false;
}
